UI/slot management
wedidtln/sopra-project-LHD pull request #86
Opened 2022-12-30 13:02 UTC by Desmondmies

Slot info Tooltip

- [ ] #55 
- [ ] #20 
- [ ] #21 
- [ ] #22

2023-01-05 20:09 UTC, anastygnome requested changes
Amazing work, if you could just get rid of the System.err calls :)

2023-01-05 20:09 UTC, anastygnome commented on edtLHD/src/main/java/fr/univtln/lhd/controllers/SlotInfoController.java
> +            System.out.println("MODIFY ERROR");
Can you please use a logger?

2023-01-05 20:09 UTC, anastygnome commented on edtLHD/src/main/java/fr/univtln/lhd/controllers/SlotInfoController.java
> +            System.out.println("DELETE ERROR");
Same here

2023-01-05 20:09 UTC, anastygnome commented on edtLHD/src/main/java/fr/univtln/lhd/controllers/SlotInfoController.java
> +            throw new RuntimeException();
Would an IllegalStateException make the sonar smell disappear?

2023-01-05 21:49 UTC, Theo-Hafsaoui approved these changes
Great work indeed

2023-01-06 09:19 UTC, anastygnome approved these changes

2023-01-06 09:20 UTC, merged